#!/usr/bin/env bash
# Cursor Cloud start script for Personal-Site.
# Runs each agent boot.  Exported shell vars do NOT persist across boots, so
# we materialize secrets into a file that the agent can `source` on demand.
#
# Output:
#   $HOME/.cursor-cloud-env/Personal-Site.env          (mode 0600, values present)
#   $HOME/.cursor-cloud-env/Personal-Site.source.sh    (one-liner: set -a; source ...; set +a)
#
# Behavior:
#   - When INFISICAL_CLIENT_ID and INFISICAL_CLIENT_SECRET are set in the
#     Cursor dashboard, log in to Infisical and export the `dev` env secrets.
#   - When the bootstrap identity is MISSING, print the missing NAMES (never
#     values) and exit 0 so the agent boot does not fail.
#   - Never print, log, or commit secret VALUES.  Names only.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

ENV_DIR="${HOME}/.cursor-cloud-env"
ENV_FILE="${ENV_DIR}/Personal-Site.env"
SOURCE_FILE="${ENV_DIR}/Personal-Site.source.sh"
INFISICAL_ENV_FILE="${REPO_ROOT}/.cursor/infisical.env"
REPO_NAME="Personal-Site"

mkdir -p "${ENV_DIR}"
chmod 0700 "${ENV_DIR}"

# Load committed non-secret Infisical coords (PROJECT_ID, ENV, DOMAIN).
# These are safe to commit; they identify the project, not the identity.
if [ -f "${INFISICAL_ENV_FILE}" ]; then
  set -a
  # shellcheck disable=SC1090
  . "${INFISICAL_ENV_FILE}"
  set +a
fi

: "${INFISICAL_DOMAIN:=https://app.infisical.com}"
: "${INFISICAL_ENV:=prod}"

# If the dashboard did not inject the bootstrap identity, name the missing
# keys and bail 0 — the agent should still boot in degraded mode.
missing=()
if [ -z "${INFISICAL_CLIENT_ID:-}" ]; then missing+=("INFISICAL_CLIENT_ID"); fi
if [ -z "${INFISICAL_CLIENT_SECRET:-}" ]; then missing+=("INFISICAL_CLIENT_SECRET"); fi
if [ "${#missing[@]}" -gt 0 ]; then
  echo "cursor-cloud-start: ${REPO_NAME} Infisical bootstrap identity missing; degraded mode." >&2
  echo "cursor-cloud-start: add these to the Cursor dashboard for ${REPO_NAME}:" >&2
  for name in "${missing[@]}"; do
    echo "  - ${name}" >&2
  done
  # Ensure stale values from a prior run are cleared.
  rm -f "${ENV_FILE}" "${SOURCE_FILE}"
  exit 0
fi

# Owner directive 2026-10-10: Infisical prod is the only environment (dev and
# staging are being retired).  Refuse anything else rather than reading it.
if [ "${INFISICAL_ENV}" != "prod" ]; then
  echo "cursor-cloud-start: INFISICAL_ENV must be prod (dev and staging are retired); refusing to load." >&2
  exit 1
fi

if ! command -v infisical >/dev/null 2>&1; then
  echo "cursor-cloud-start: infisical CLI not found on PATH; install during Build (scripts/cursor-cloud-install.sh)." >&2
  echo "cursor-cloud-start: add the INFISICAL_CLIENT_ID / INFISICAL_CLIENT_SECRET to the Cursor dashboard for ${REPO_NAME}." >&2
  rm -f "${ENV_FILE}" "${SOURCE_FILE}"
  exit 0
fi

echo "==> Fetching Infisical secrets (${INFISICAL_ENV}) for ${REPO_NAME}"

# Login with universal auth (non-interactive).  The -p secret flag keeps the
# value out of argv-based process listings where supported.
infisical login \
  --method=universal-auth \
  --client-id="${INFISICAL_CLIENT_ID}" \
  --client-secret="${INFISICAL_CLIENT_SECRET}" \
  --domain="${INFISICAL_DOMAIN}" \
  --silent \
  --plain >/dev/null

# Export secrets for the configured env.  We pipe through a tmpfile, then
# tighten perms and move into place.  Values never go to stdout/stderr.
TMP_FILE="$(mktemp "${ENV_DIR}/.${REPO_NAME}.env.tmp.XXXXXX")"
chmod 0600 "${TMP_FILE}"

# shellcheck disable=SC2086
infisical export \
  --env="${INFISICAL_ENV}" \
  --projectId="${INFISICAL_PROJECT_ID}" \
  --domain="${INFISICAL_DOMAIN}" \
  --format=dotenv \
  >"${TMP_FILE}" 2>/dev/null

# Sanity: the export must be a non-empty dotenv.  Otherwise something failed
# upstream and we should not leave a half-written file in place.
if [ ! -s "${TMP_FILE}" ]; then
  echo "cursor-cloud-start: infisical export returned no rows for env=${INFISICAL_ENV}; clearing ${ENV_FILE}." >&2
  rm -f "${TMP_FILE}" "${ENV_FILE}" "${SOURCE_FILE}"
  exit 0
fi

mv "${TMP_FILE}" "${ENV_FILE}"
chmod 0600 "${ENV_FILE}"

# Write the helper sourcer.  We use a fixed, single-line form so a `cat` of
# the file is obviously safe; the env file itself stays out of transcripts.
cat >"${SOURCE_FILE}" <<EOF
#!/usr/bin/env bash
# Auto-generated by scripts/cursor-cloud-start.sh.  Source this to load
# Personal-Site Infisical secrets into the current shell.  Values are NOT
# printed.
set -a
# shellcheck disable=SC1090
. "${ENV_FILE}"
set +a
EOF
chmod 0600 "${SOURCE_FILE}"

echo "==> Wrote ${ENV_FILE} (0600) and ${SOURCE_FILE}"
echo "==> Source secrets in a new shell with: . ${SOURCE_FILE}"
